server:
  port: 8090

spring:
  aplication:
    name: mcsv-student
  datasource:
    drive-class-name: com.mysql.cj.jdbc.drive
    url: jdbc:mysql://localhost/studentsDB
    username: root
    password: 1301
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.MySQL8Dialect
  config:
    import: opcional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
