server:
  port: 8090

spring:
  application:
    name: mcsv-student
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentsDB
    username: root
    password: 1301
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.MySQL8Dialect
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
