server:
  port: 8761

spring:
  aplication:
    name: msvc-eureka

eureka:
  instance: 
    hostname: localhost
  client:
    registrer-with-uereka: false
    fetch-registry: false
    server-url:
      defaultZone:http://localhost:${server.port}/eureka/