server:
  port: 9090

spring:
  aplication:
    name: mcsv-courses
  datasource:
    drive-class-name: org.postgresql.drive
    url: jdbc:postgresql://localhost/coursesDB
    username: postgre
    password: 1301
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.postgreSQLDialect
  config:
    import: opcional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
